"""
Plan Exporter — generates a well-formatted plan.md
from the pipeline results.
"""

from datetime import datetime


def export_plan(results: dict) -> str:
    """
    Generate a Markdown plan document from pipeline results.

    Args:
        results: Full pipeline output with all stage results

    Returns:
        Formatted Markdown string
    """
    occupation = results.get("occupation", "Unknown")
    idea = results.get("idea", "Unknown")
    timestamp = results.get("timestamp", datetime.now().isoformat())
    stages = results.get("stages", {})

    brainstorm_content = stages.get("brainstorm", {}).get("content", "N/A")
    sentiment_content = stages.get("sentiment", {}).get("content", "N/A")
    niche_content = stages.get("niche", {}).get("content", "N/A")
    mvp_content = stages.get("mvp", {}).get("content", "N/A")

    plan = f"""# 🧠 PRODUCT THINKER — MVP Plan

> Generated by PRODUCT THINKER AI
> **Date:** {_format_date(timestamp)}
> **Occupation:** {occupation}
> **Original Idea:** {idea}

---

## Stage 1: Brainstormed Ideas

{brainstorm_content}

---

## Stage 2: Market Sentiment Analysis

{sentiment_content}

---

## Stage 3: Niche Discovery & Market Opportunity

{niche_content}

---

## Stage 4: MVP Plan

{mvp_content}

---

*This plan was generated by PRODUCT THINKER using Qwen3 deep thinking
with real-time web data analysis. Use it as a starting point —
validate assumptions with real customers before building.*
"""
    return plan


def _format_date(iso_string: str) -> str:
    """Convert ISO timestamp to readable date."""
    try:
        dt = datetime.fromisoformat(iso_string)
        return dt.strftime("%B %d, %Y at %I:%M %p")
    except (ValueError, TypeError):
        return iso_string
